### ISSUE TITLE
rational equality

### ISSUE THREAD

**Issue by fibo** [substack/bigint-rational#1]
I am implementing something similar to this.

It looks like you are not using the same way to copmare two rationals, maybe you want to check out my implementation here: https://github.com/fibo/algebra#scalar

Equality can be defined as:

```js
const equality = ([n1, d1], [n2, d2]) => (n1 * d2 === n2 * d1)
```

**Comment by substack** [comment]
The compare function is very similar:

``` js
var bn = require('./lib/bn.js')

module.exports = function compare (a, b) {
  var x = a[0] * bn.abs(b[1]) * bn.sign(a[1])
  var y = b[0] * bn.abs(a[1]) * bn.sign(b[1])
  if (x === y) return 0
  return x < y ? -1 : +1
}
```

I guess those abs() and signs() could be eliminated (I think there used to be some other conditions handled that got simplified) but other than that it's the same technique, unless I'm missing something.

**Comment by fibo** [comment]
Yes, a part abs and sign is the same condition, by the way the same you find on wikipedia here: https://en.wikipedia.org/wiki/Rational_number
